//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSL.Scraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolImageData
    {
        public int Sol { get; set; }
        public string Cam { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageUrl { get; set; }
    }
}
